[build]
  command = """
    python -m venv .venv &&
    . .venv/bin/activate &&
    pip install --upgrade pip &&
    pip install -r requirements.txt &&
    pelican content -o output -s publishconf.py
  """
  publish = "output"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
